## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('udp-echo', ['csma', 'internet', 'applications'])
    obj.source = 'udp-echo.cc'
    obj = bld.create_ns3_program('vehicle-demo', ['csma', 'internet', 'applications','core', 'mobility', 'wifi', 'stats'])
    obj.source = 'vehicle-demo.cc'
